import { Dimensions, StyleSheet } from "react-native";
const { width, height } = Dimensions.get("window");

const authStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "#0f172a",
  },
  backgroundImage: {
    flex: 1,
  },
  backgroundOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.62)",
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 32,
  },
  topBrand: {
    alignItems: "center",
    marginBottom: 18,
  },
  container: {
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
    borderRadius: 28,
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    paddingHorizontal: 20,
    paddingVertical: 24,
    shadowColor: "#020617",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.2,
    shadowRadius: 28,
    elevation: 8,
  },
  logoWrap: {
    width: 78,
    height: 78,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    marginBottom: 14,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 5,
  },
  title: {
    fontSize: 14,
    fontFamily: "Jost-SemiBold",
    textAlign: "center",
    marginBottom: 6,
    color: "#dbeafe",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  LogoTitle: {
    fontSize: 32,
    fontFamily: "Jost-Bold",
    color: "#ffffff",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 15,
    fontFamily: "Jost-Regular",
    color: "#dbeafe",
    textAlign: "center",
    lineHeight: 22,
    maxWidth: 360,
    marginTop: 10,
  },
  cardTitle: {
    fontSize: 24,
    fontFamily: "Jost-Bold",
    color: "#0f172a",
    textAlign: "center",
    marginBottom: 6,
  },
  cardSubtitle: {
    fontSize: 14,
    fontFamily: "Jost-Regular",
    color: "#475569",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 18,
  },
  fieldGroup: {
    width: "100%",
    marginBottom: 10,
  },
  helperRow: {
    width: "100%",
    alignItems: "flex-end",
    marginTop: 4,
    marginBottom: 10,
  },
  helperRowCenter: {
    width: "100%",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 6,
  },
  helperText: {
    fontFamily: "Jost-Regular",
    fontSize: 13,
    color: "#64748b",
    textAlign: "center",
  },
  logo: {
    width: 58,
    height: 58,
  },
  Loginlogo: {
    width: width * 0.25,
    zIndex: 5,
    height: height * 0.13,
    alignSelf: "center",
    borderRadius: 20,
    marginVertical: "2%",
    // position: "absolute",
    // top: 105,
  },
  otpView: {
    marginTop: 10,
    marginBottom: 4,
  },
  otpicView: {
    alignItems: "center",
  },
  otpInput: {
    width: 56,
    height: 58,
    color: "#0b57a4",
    marginHorizontal: 6,
    fontSize: 22,
    textAlign: "center",
    fontFamily: "Jost-Medium",
    borderWidth: 1.5,
    borderColor: "#cbd5e1",
    borderRadius: 16,
    backgroundColor: "#ffffff",
  },
  otpres: {
    color: "#14813d",
    fontSize: 16,
    fontFamily: "Jost-SemiBold",
  },
  flexRow: {
    flexDirection: "row",
    justifyContent: "center",
  },
  resendLink: {
    fontFamily: "Jost-SemiBold",
    fontSize: 14,
    color: "#0b57a4",
    textAlign: "center",
  },
  ffJost: {
    fontFamily: "Jost-Medium",
    textAlign: "center",
    fontSize: 14,
    color: "#0b57a4",
  },
  ffPopSemi: {
    fontFamily: "Jost-SemiBold",
  },
  bnavLinks: {
    flexDirection: "row",
    justifyContent: "center",
    width: "100%",
  },
  regLinkBox: {
    marginTop: 4,
    marginBottom: 6,
  },
  errTxt: {
    color: "#b91c1c",
    fontSize: 12,
    fontFamily: "Jost-Medium",
    marginTop: 6,
  },
  inpErr: {
    width: "100%",
    color: "#b91c1c",
    fontSize: 12,
    marginTop: 6,
    textAlign: "left",
    fontFamily: "Jost-Medium",
    marginBottom: 2,
  },
  otpErrView: {
    marginTop: 10,
  },
  bottomImg: {
    width: width,
    bottom: 0,
    height: height * 0.18,
    position: "absolute",
    alignSelf: "center",
  },
  match: {
    fontWeight: "bold",
    color: "#b91c1c",
    fontSize: 12,
    marginVertical: 10,
  },
});

export default authStyles;
