import { StyleSheet } from "react-native";

import { colors, radius, shadows, spacing } from "@/constants/theme";

const styles = StyleSheet.create({
  table: {
    flex: 1,
    marginHorizontal: spacing.md,
    marginTop: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
    ...shadows.card,
  },
  toolbar: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  searchContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    minHeight: 48,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontFamily: "Jost-Regular",
    fontSize: 14,
    color: colors.text,
  },
  filterToggleButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 14,
  },
  filterToggleActive: {
    borderColor: "#bfd4f7",
    backgroundColor: colors.primarySoft,
  },
  filterToggleText: {
    fontFamily: "Jost-SemiBold",
    fontSize: 13,
    color: colors.textMuted,
  },
  filterToggleTextActive: {
    color: colors.primary,
  },
  filterCountBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  filterCountText: {
    fontFamily: "Jost-Bold",
    fontSize: 11,
    color: "#fff",
  },
  filterPanel: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    padding: spacing.md,
  },
  filterHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  filterPanelTitle: {
    fontFamily: "Jost-Bold",
    fontSize: 15,
    color: colors.text,
  },
  clearAllText: {
    fontFamily: "Jost-SemiBold",
    fontSize: 12,
    color: colors.primary,
  },
  filterGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  filterField: {
    width: "48%",
  },
  filterFieldLabel: {
    marginBottom: 6,
    fontFamily: "Jost-SemiBold",
    fontSize: 12,
    color: colors.text,
  },
  filterInput: {
    minHeight: 44,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    fontFamily: "Jost-Regular",
    fontSize: 13,
    color: colors.text,
  },
  procurementSection: {
    marginTop: spacing.md,
  },
  procurementChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  procurementChip: {
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  procurementChipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  procurementChipText: {
    fontFamily: "Jost-Medium",
    fontSize: 12,
    color: colors.textMuted,
  },
  procurementChipTextActive: {
    color: colors.primary,
  },
  activeFiltersWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
  },
  activeFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: "#bfd4f7",
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  activeFilterText: {
    fontFamily: "Jost-Medium",
    fontSize: 12,
    color: colors.primary,
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#e6effc",
    borderTopWidth: 1,
    borderTopColor: colors.border,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  headerCell: {
    flex: 1.6,
    fontFamily: "Jost-Bold",
    fontSize: 13,
    color: colors.text,
  },
  headerCellRight: {
    flex: 1,
    textAlign: "center",
    fontFamily: "Jost-Bold",
    fontSize: 13,
    color: colors.text,
  },
  listContent: {
    paddingBottom: spacing.md,
    height:"auto",
    minHeight: 780,
  },
  projectCard: {
    flexDirection: "row",
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  projectCardFirst: {
    borderTopWidth: 0,
  },
  projectDetailsColumn: {
    flex: 1.6,
  },
  actionColumn: {
    flex: 1,
    justifyContent: "center",
  },
  projectTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  projectTitleWrap: {
    flex: 1,
    flexDirection: "row",
    gap: 8,
  },
  projectIconBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primarySoft,
    marginTop: 1,
  },
  projectName: {
    flex: 1,
    fontFamily: "Jost-SemiBold",
    fontSize: 14,
    lineHeight: 20,
    color: colors.text,
  },
  projectMetaChips: {
    alignItems: "flex-end",
    gap: 6,
  },
  projectMetaChip: {
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  projectMetaChipText: {
    fontFamily: "Jost-SemiBold",
    fontSize: 10,
    color: colors.textMuted,
    textTransform: "uppercase",
  },
  projectStatusChip: {
    backgroundColor: colors.successSoft,
    borderColor: "#cdeed7",
  },
  projectStatusChipText: {
    fontFamily: "Jost-SemiBold",
    fontSize: 10,
    color: colors.success,
    textTransform: "uppercase",
  },
  expandToggle: {
    alignSelf: "flex-start",
    marginTop: 6,
  },
  expandToggleText: {
    fontFamily: "Jost-Medium",
    fontSize: 12,
    color: colors.primary,
  },
  metricInlineRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  metricInlineLabel: {
    fontFamily: "Jost-SemiBold",
    fontSize: 12,
    color: colors.text,
  },
  contractValueText: {
    fontFamily: "Jost-Bold",
    fontSize: 12,
    color: colors.success,
  },
  progressBlock: {
    marginBottom: spacing.sm,
  },
  progressHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  progressLabel: {
    fontFamily: "Jost-SemiBold",
    fontSize: 12,
    color: colors.text,
  },
  progressValue: {
    fontFamily: "Jost-Bold",
    fontSize: 12,
    color: colors.textMuted,
  },
  progressTrack: {
    overflow: "hidden",
    borderRadius: 10,
  },
  progressShimmer: {
    flex: 1,
    borderRadius: 10,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 38,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: radius.md,
    marginBottom: 10,
  },
  actionButtonDisabled: {
    opacity: 0.55,
  },
  actionIcon: {
    marginRight: 6,
  },
  actionButtonText: {
    color: "#fff",
    fontFamily: "Jost-SemiBold",
    fontSize: 12,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
  },
  emptyStateTitle: {
    fontFamily: "Jost-Bold",
    fontSize: 16,
    color: colors.text,
    textAlign: "center",
  },
  emptyStateText: {
    marginTop: 8,
    fontFamily: "Jost-Regular",
    fontSize: 13,
    lineHeight: 19,
    color: colors.textMuted,
    textAlign: "center",
  },
  footerSpace: {
    height: spacing.lg,
  },
  skeletonRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
    paddingHorizontal: spacing.md,
  },
  skeletonTextWrap: {
    marginLeft: 10,
    flex: 1,
  },
  skeletonBlock: {
    marginBottom: 6,
  },
});

export default styles;
