import { StyleSheet } from "react-native";
import { width, height } from "../../../services/helper";

const styles = StyleSheet.create({
  table: {
    flexDirection: "column",
    marginHorizontal: "2%",
    marginVertical: "3%",
    borderRadius: 5,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  row: {
    flexDirection: "row",
  },
  headerSnoCell: {
    width: width * 0.12,
    // flex: 1,
    paddingHorizontal: "1%",
    paddingVertical: "3%",
    fontFamily: "Jost-SemiBold",
    backgroundColor: "#f0f0f0",
    textAlign: "center",
  },
  headerCell: {
    // width: width * 0.26,
    flex: 1,
    // paddingHorizontal: "2%",
    paddingLeft: "5%",
    paddingVertical: "3%",
    fontFamily: "Jost-SemiBold",
    backgroundColor: "#f0f0f0",
    textAlign: "center",
    fontSize: 13,
  },
  snocellView: {
    width: width * 0.1,
    paddingHorizontal: "1%",
    paddingVertical: "3%",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    alignItems: "center",
    justifyContent: "center",
  },
  snocell: {
    textAlign: "center",
    fontFamily: "Jost-Medium",
  },
  cellNameView: {
    width: width * 0.5,
    // flex: 1,
    // alignItems: "center",
    justifyContent: "center",
    paddingLeft: "2.5%",
    paddingRight: "5%",
    // paddingHorizontal: "2%",
    paddingVertical: "2%",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    // backgroundColor: "red",
  },
  cellView: {
    width: width * 0.3,
    // flex: 1,
    alignItems: "center",
    // justifyContent: "center",
    paddingHorizontal: "1%",
    paddingVertical: "2%",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    // backgroundColor: "green",
  },
  cell: {
    // textAlign: "center",
    fontFamily: "Jost-Regular",
    fontSize: 12,
  },
  buttonView: {
    width: width * 0.25,
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: "center",
    backgroundColor: "#007bff",
    padding: "5%",
    // paddingVertical: "2%",
    borderRadius: 4,
  },
  card: {
    backgroundColor: "#fff",
    padding: 15,
    marginBottom: 15,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 5,
    color: "#333",
  },
  contract: {
    fontSize: 12,
    marginBottom: 12,
    color: "green",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  label: {
    fontSize: 11,
    fontWeight: "500",
  },
  value: {
    fontSize: 12,
    fontWeight: "500",
    color: "#444",
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    minWidth: "40%",
    marginBottom: 8,
  },
  buttonText: {
    color: "#fff",
    fontFamily: "Jost-Medium",
    fontSize: 13,
  },
});

export default styles;
